spring:
  jpa:
    hibernate:
      ddl-auto: create-drop

  datasource:
    url: jdbc:h2:mem:addressbook;MODE=PostgreSQL
    username: sa
    password: sa
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
